apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iso-client
  name: iso-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iso-client
  template:
    metadata:
      labels:
        app: iso-client
    spec:
      containers:
        - image: andrianrf/iso-client:latest
          imagePullPolicy: IfNotPresent
          name: iso-client
          ports:
            - containerPort: 8100
          envFrom:
            - configMapRef:
                name: bpjstk-cm
          env:
            - name: "isoServerUrl"
              value: "iso-server"
            - name: "isoServerPort"
              value: "8828"
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
            limits:
              memory: "300Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8100
            initialDelaySeconds: 195
            periodSeconds: 15
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: iso-client
  labels:
    app: iso-client
spec:
  type: ClusterIP
  selector:
    app: iso-client
  ports:
    - name: 8100-tcp
      protocol: TCP
      port: 8100
      targetPort: 8100
