apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backoffice-be
  name: backoffice-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-be
  template:
    metadata:
      labels:
        app: backoffice-be
    spec:
      containers:
        - image: andrianrf/backoffice-be:latest
          imagePullPolicy: IfNotPresent
          name: backoffice-be
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: bpjstk-cm
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
            limits:
              memory: "300Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /va-tools-be/actuator/health
              port: 8089
            initialDelaySeconds: 195
            periodSeconds: 15
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: backoffice-be
  labels:
    app: backoffice-be
spec:
  type: ClusterIP
  selector:
    app: backoffice-be
  ports:
    - name: 8089-tcp
      protocol: TCP
      port: 8089
      targetPort: 8089
