apiVersion: v1
kind: ConfigMap
metadata:
  name: backoffice-nginx-config
data:
  backoffice.conf: |
    server {
      listen 8080 default_server;
      server_name localhost;
      root /usr/share/nginx/html;
      index index.html;

      gzip on;
      gzip_disable "msie6";

      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 9;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
      gzip_min_length 0;
      gzip_types text/plain application/javascript text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype;

      location / {
    return 301 /backoffice;
      }

      location /backoffice {
          try_files $uri $uri/backoffice /backoffice/index.html;
      }

      location /va-tools-be {
          proxy_pass http://backoffice-be:8089;
          proxy_set_header    Host               $host;
          proxy_set_header    X-Real-IP          $remote_addr;
          proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Host   $host;
          proxy_set_header    X-Forwarded-Server $host;
          proxy_set_header    X-Forwarded-Port   $server_port;
          proxy_set_header    X-Forwarded-Proto  $scheme;
      }
    
      location /va-gateway/1.0/transfer-va {
          proxy_pass http://va-gateway.va.svc.cluster.local:8081;
          proxy_set_header    Host               $host;
          proxy_set_header    X-Real-IP          $remote_addr;
          proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Host   $host;
          proxy_set_header    X-Forwarded-Server $host;
          proxy_set_header    X-Forwarded-Port   $server_port;
          proxy_set_header    X-Forwarded-Proto  $scheme;
      }
    
      # location /api/providers {
      #     proxy_pass http://provider-service:8081;
      #     proxy_set_header    Host               $host;
      #     proxy_set_header    X-Real-IP          $remote_addr;
      #     proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
      #     proxy_set_header    X-Forwarded-Host   $host;
      #     proxy_set_header    X-Forwarded-Server $host;
      #     proxy_set_header    X-Forwarded-Port   $server_port;
      #     proxy_set_header    X-Forwarded-Proto  $scheme;
      # }
    
      # location /api/inquiryTrxVA {
      #     proxy_pass http://tulip:8081;
      #     proxy_set_header    Host               $host;
      #     proxy_set_header    X-Real-IP          $remote_addr;
      #     proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
      #     proxy_set_header    X-Forwarded-Host   $host;
      #     proxy_set_header    X-Forwarded-Server $host;
      #     proxy_set_header    X-Forwarded-Port   $server_port;
      #     proxy_set_header    X-Forwarded-Proto  $scheme;
      # }
    
      # location /api/executeTrxVA {
      #     proxy_pass http://tulip:8081;
      #     proxy_set_header    Host               $host;
      #     proxy_set_header    X-Real-IP          $remote_addr;
      #     proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
      #     proxy_set_header    X-Forwarded-Host   $host;
      #     proxy_set_header    X-Forwarded-Server $host;
      #     proxy_set_header    X-Forwarded-Port   $server_port;
      #     proxy_set_header    X-Forwarded-Proto  $scheme;
      # }
    
      # location /api/inquiry-intrabank {
      #     proxy_pass http://tulip:8081;
      #     proxy_set_header    Host               $host;
      #     proxy_set_header    X-Real-IP          $remote_addr;
      #     proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
      #     proxy_set_header    X-Forwarded-Host   $host;
      #     proxy_set_header    X-Forwarded-Server $host;
      #     proxy_set_header    X-Forwarded-Port   $server_port;
      #     proxy_set_header    X-Forwarded-Proto  $scheme;
      # }
    
      # location /api/transfer-va/payment-intrabank {
      #     proxy_pass http://tulip:8081;
      #     proxy_set_header    Host               $host;
      #     proxy_set_header    X-Real-IP          $remote_addr;
      #     proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
      #     proxy_set_header    X-Forwarded-Host   $host;
      #     proxy_set_header    X-Forwarded-Server $host;
      #     proxy_set_header    X-Forwarded-Port   $server_port;
      #     proxy_set_header    X-Forwarded-Proto  $scheme;
      # }

      location /bpjstk-service {
          proxy_pass http://bpjstk-service:8091;
          proxy_set_header    Host               $host;
          proxy_set_header    X-Real-IP          $remote_addr;
          proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Host   $host;
          proxy_set_header    X-Forwarded-Server $host;
          proxy_set_header    X-Forwarded-Port   $server_port;
          proxy_set_header    X-Forwarded-Proto  $scheme;
      }


      location /static/ {
        try_files
          /backoffice$uri
          =404;
      }

      error_page 404 /404.html;
      location = /404.html {
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backoffice
  name: backoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice
  template:
    metadata:
      labels:
        app: backoffice
    spec:
      containers:
        - image: andrianrf/backoffice:latest
          imagePullPolicy: IfNotPresent
          name: backoffice
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
            limits:
              memory: "300Mi"
              cpu: "250m"
          volumeMounts:
            - name: application-config
              mountPath: "/etc/nginx/conf.d/nginx.conf"
              subPath: "nginx.conf"
              readOnly: true
      # kubectl create configmap backoffice-nginx-config --from-file="C:\\Users\\AndrianRF\\Desktop\bpjstk bsb\\deployment\\1. docker\\backoffice.conf"
      volumes:
        - name: application-config
          configMap:
            name: backoffice-nginx-config
            items:
              - key: backoffice.conf
                path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
  name: backoffice
  labels:
    app: backoffice
spec:
  type: ClusterIP
  selector:
    app: backoffice
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
